#!/usr/bin/env python3
import json
import time
import os

RESULTS_FILE = "research_results.jsonl"

def clear_terminal():
    os.system('cls' if os.name == 'nt' else 'clear')

def track_and_evaluate():
    while True:
        if not os.path.exists(RESULTS_FILE):
            clear_terminal()
            print(f"[!] Waiting for {RESULTS_FILE} to be generated by the first batch...")
            time.sleep(2)
            continue

        # Use a dictionary to deduplicate logs across multiple batch overlaps
        processed_logs = {}
        
        with open(RESULTS_FILE, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    data = json.loads(line)
                    # The line_no is the unique ID. This overwrites duplicates safely.
                    processed_logs[data["line_no"]] = data
                except (json.JSONDecodeError, KeyError):
                    continue

        if not processed_logs:
            time.sleep(2)
            continue

        # Initialize math counters
        tp, fp, tn, fn = 0, 0, 0, 0
        total_time = 0.0
        
        # Calculate metrics strictly from the deduplicated history
        for data in processed_logs.values():
            total_time += data.get("triage_time_seconds", 0)
            
            ground_truth = data.get("ground_truth", "UNKNOWN").upper()
            predicted_threat = data.get("is_threat_prediction", True)
            
            is_actual_threat = ground_truth not in ["BENIGN", "NONDOH"]
            
            if is_actual_threat and predicted_threat: tp += 1
            elif not is_actual_threat and predicted_threat: fp += 1
            elif not is_actual_threat and not predicted_threat: tn += 1
            elif is_actual_threat and not predicted_threat: fn += 1

        total_unique_logs = len(processed_logs)
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
        mttt = total_time / total_unique_logs if total_unique_logs > 0 else 0.0

        # Render Dashboard
        clear_terminal()
        print("=====================================================================")
        print(" 🔴 BATCH SOC EVALUATION DASHBOARD | CUMULATIVE METRICS")
        print("=====================================================================")
        print(f"  Unique Logs Evaluated : {total_unique_logs:>6,}")
        print(f"  Cumulative Triage Time: {total_time:>6.1f}s")
        print(f"  Mean Triage Time      : {mttt:>6.2f}s per log\n")
        
        print("  --- CUMULATIVE CONFUSION MATRIX ---")
        print(f"  True Positives (TP)  : \033[92m{tp:>5,}\033[0m (Accurate Threat Detections)")
        print(f"  False Positives (FP) : \033[93m{fp:>5,}\033[0m (Benign flagged as threat)")
        print(f"  True Negatives (TN)  : \033[92m{tn:>5,}\033[0m (Benign safely ignored)")
        print(f"  False Negatives (FN) : \033[91m{fn:>5,}\033[0m (Threats missed by system)\n")
        
        print("  --- RESEARCH METRICS ---")
        print(f"  Precision : {precision:.4f}  (Higher = Less Alert Fatigue)")
        print(f"  Recall    : {recall:.4f}  (Higher = Fewer Missed Attacks)")
        print(f"  F1-Score  : \033[96m{f1_score:.4f}\033[0m  (Overall System Accuracy)")
        print("=====================================================================")
        print(" Press Ctrl+C to exit dashboard. Auto-updating every 2 seconds...\n")
        
        time.sleep(2)

if __name__ == "__main__":
    try:
        track_and_evaluate()
    except KeyboardInterrupt:
        print("\n[!] Exiting Cumulative Dashboard.")